cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/core'
tap 'homebrew/devel-only'
tap 'homebrew/services'
tap 'homebrew/x11'
tap 'koekeishiya/formulae'
tap 'neovim/neovim'

brew 'aria2'
brew 'autoconf'  # the_silver_searcher
brew 'bc'  # linux
brew 'clang-format'
brew 'cloc'
brew 'cmus'
brew 'elm-format', args: ['devel']
brew 'fish'
brew 'fontconfig'  # graphviz
brew 'freetype'  # graphviz
brew 'gd'  # graphviz
brew 'gdbm'  # python3
brew 'gettext'  # neovim
brew 'glide'
brew 'gmp'  # swi-prolog
brew 'go'
brew 'graphviz'
brew 'heroku'
brew 'hub'
brew 'icu4c'  # node
brew 'jpeg'  # graphviz
brew 'libevent'  # tmux
brew 'libpng'  # graphviz
brew 'libtermkey'  # neovim
brew 'libtiff'  # graphviz
brew 'libtool'  # graphviz
brew 'libuv'  # neovim
brew 'libvterm'  # neovim
brew 'lynis'
brew 'mitmproxy'
brew 'mobile-shell'
brew 'mplayer'
brew 'msgpack'  # neovim
brew 'neovim', args: ['HEAD']
brew 'nmap'
brew 'node'  # macos
brew 'openssl'  # python
brew 'pandoc'
brew 'pcre'  # the_silver_searcher
brew 'pcre2' # fish
brew 'pkgconfig'
brew 'postgresql'  # macos
brew 'protobuf'  # mobile-shell
brew 'python'
brew 'python3'
brew 'readline'  # postgresql  # macos
brew 'reattach-to-user-namespace'  # macos
brew 'redis'
brew 'sqlite'
brew 'swi-prolog', args: ['HEAD']
brew 'the_silver_searcher'
brew 'tmux'
brew 'tmux-mem-cpu-load'
brew 'tree'
brew 'unibilium'  # neovim
brew 'utf8proc'  # tmux
brew 'watch'  # macos
brew 'webp'  # graphviz
brew 'xz'  # linux # the_silver_searcher

cask 'appcleaner'
cask 'dash'
cask 'firefox'
cask 'grandperspective'
cask 'kindle'
cask 'skim'
cask 'skype'
cask 'slack'
cask 'steam'
cask 'teensy'
cask 'thunderbird'
cask 'torbrowser'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
cask 'yubico-authenticator'
cask 'yubikey-personalization-gui'
cask 'yubikey-piv-manager'
