#!/bin/sh
set -e

_vim() {
  echo "Create temp and swap folder for vim"
  VIM_DIRS="vim vim/backup vim/swap vim/bundle"
  for vim_dir in $VIM_DIRS
  do
    mkdir -p "$PWD/$vim_dir"
  done
  echo "Checking if Vundle exists"
  if [ ! -e vim/bundle/Vundle.vim ]
  then
    git clone git@github.com:gmarik/Vundle.vim.git vim/bundle/Vundle.vim
  fi
  echo "Installing Plugings with Vundle"
  vim +PluginInstall +qall
}

_symlinks() {
  echo "Making symlinks"
  symlinks="tmux.conf vim vimrc latexmkrc screenrc zshrc"
  for s in $symlinks
  do
    echo "Linking $s"
    ln -sf "$PWD/$s" "$HOME/.$s"
  done
  wait
}

_chsh() {
  echo "Checking default shell"
  ZSH_PATH=$(which zsh)
  if [ "$SHELL" != "$ZSH_PATH" ]
  then
    echo "Set $ZSH_PATH as default shell"
    chsh -s "$ZSH_PATH"
  fi
  echo "Done"
}

_git() {
  git config --global push.default simple
  git config --global commit.template "$PWD/gitmessage"
  git config --global core.editor /usr/bin/vim
  git submodule init
  git submodule update
}

if [ "$(uname)" != "Darwin" ]
then
  if ! zsh
  then
    echo "Please install zsh"
    exit 1
  fi
fi
_chsh &
_symlinks &
_git &
wait
_vim
