#!/bin/sh
set -e

_vim() {
  echo "Create temp and swap folder for vim"
  mkdir -p $PWD/vim
  mkdir -p $PWD/vim/backup
  mkdir -p $PWD/vim/swap
  mkdir -p $PWD/vim/bundle
  echo "Checking if Vundle exists"
  if [ ! -e vim/bundle/Vundle.vim ]
  then
    git clone git@github.com:gmarik/Vundle.vim.git vim/bundle/Vundle.vim
  fi
  echo "Installing Plugings with Vundle"
  vim +PluginInstall +qall
}

_symlinks() {
  echo "Making symlinks"
  symlinks="vim vimrc latexmkrc screenrc zshrc"
  for s in $symlinks
  do
    echo "Linking $s"
    ln -sf $PWD/$s ~/.$s
  done
  wait
}

_chsh() {
  echo "Checking default shell"
  ZSH_PATH=`which zsh`
  if [ $SHELL != $ZSH_PATH ]
  then
    echo "Set $ZSH_PATH as default shell"
    chsh -s $ZSH_PATH
  fi
  echo "Done"
}

_git() {
  git config --global push.default simple
  git config --global commit.template $PWD/gitmessage
  git config --global core.editor /usr/bin/vim
}

if [ `uname` = 'Darwin' ]
then
  _chsh &
fi
_symlinks &
_git &
wait
_vim
