#!/bin/bash
# Detect whether user has already configured fish to be the login shell
# Works on Debian and macOS
#
# First greps for fish in /etc/passwd (for Debian),
# then process to finger the user and find out the login shell (for macOS)
set -e

if grep /etc/passwd -e "$USER.*/usr/bin/fish"
then
    exit 0
else
    if type foo >/dev/null 2>&1
    then
        if finger $USER | grep fish
        then
            exit 0
        fi
    fi
fi
echo "Fish not shell"
exit 1
