# SPDX-FileCopyrightText: 2014-2025 Justus Perlwitz
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/helium--nixos--vg-nixos--root";
    fsType = "ext4";
  };

  fileSystems."/nix" = {
    device = "/nix";
    fsType = "none";
    options = [ "bind" ];
  };

  fileSystems."/etc" = {
    device = "/dev/mapper/helium--nixos--vg-etc";
    fsType = "ext4";
  };

  fileSystems."/var" = {
    device = "/dev/mapper/helium--nixos--vg-var";
    fsType = "ext4";
  };

  fileSystems."/nix/store" = {
    device = "/nix/store";
    fsType = "none";
    options = [ "bind" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/aff0df62-b55a-4410-b7ef-8f933f795f42";
    fsType = "ext2";
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/C5DD-F6E4";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/var/lib/bitcoind-default" = {
    device = "/dev/mapper/helium--post--boot--vg-bitcoind";
    fsType = "ext4";
  };

  fileSystems."/home" = {
    device = "/dev/mapper/helium--post--boot--vg-home";
    fsType = "ext4";
  };

  fileSystems."/srv/borgbackup" = {
    device = "/dev/mapper/helium--post--boot--vg-borgbackup";
    fsType = "ext4";
  };

  swapDevices = [
    { device = "/dev/mapper/helium--nixos--vg-swap"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
