# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/17d39f71-7f41-45c4-87cb-fda27e54111d";
      fsType = "ext4";
    };

  fileSystems."/etc" =
    {
      device = "/dev/disk/by-uuid/495321d4-6167-430b-8a8f-77e4295867e5";
      fsType = "ext4";
    };

  fileSystems."/nix" =
    {
      device = "/nix";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/var" =
    {
      device = "/dev/disk/by-uuid/104adddb-63aa-4f5a-8a3a-473391b077b3";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/aff0df62-b55a-4410-b7ef-8f933f795f42";
      fsType = "ext2";
    };

  fileSystems."/boot/efi" =
    {
      device = "/dev/disk/by-uuid/C5DD-F6E4";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/331513f1-1be3-45b1-b3c9-b11e4772e36a";
      fsType = "ext4";
    };

  fileSystems."/srv/borgbackup" =
    {
      device = "/dev/disk/by-uuid/e96f462e-bd88-44e2-a3af-d8c542e80dab";
      fsType = "ext4";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/bf078544-06c2-4690-845e-526c0df6aede"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.virbr0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
