# tap repositories and their packages

tap caskroom/cask
brew brew-cask
cask appcleaner
cask balsamiq-mockups
cask coconutbattery
cask google-chrome
cask osxfuse
cask skype
cask virtualbox

tap neovim/neovim
brew neovim

tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew ansible
brew aspell
brew fish
brew imagemagick --with-x11 --with-x11
brew neovim
brew youtube-dl

# App Store applications
appstore BetterSnapTool
appstore Dash
appstore Numbers
