# SPDX-FileCopyrightText: 2026 Justus Perlwitz
# SPDX-License-Identifier: GPL-3.0-or-later
[whipper.cd.rip]
output_directory = ~/annex/Music/Music_Files/cdrips/whipper
# man whipper-cd-rip
# Tracks are named according to the track template, filling in the variables
# and adding the file extension. Variables exclusive to the track template are:
#
# - %t: track number
# - %a: track artist
# - %n: track title
# - %s: track sort name
#
# Disc files (.cue, .log, .m3u) are named according to the disc template,
# filling in the variables and adding the file extension. Variables for both
# disc and track template are:
#
# - %A: release artist
# - %S: release sort name
# - %B: release barcode
# - %C: release catalog number
# - %c: release disambiguation comment
# - %d: release title (with disambiguation)
# - %D: disc title (without disambiguation)
# - %I: MusicBrainz Disc ID
# - %M: total number of discs in the chosen release
# - %N: number of current disc
# - %T: medium title
# - %y: release year
# - %r: release type, lowercase
# - %R: release type, normal case
# - %x: audio extension, lowercase
# - %X: audio extension, uppercase
#
# Paths to track files referenced in .cue and .m3u files will be made
# relative to the directory of the disc files.
# See also
# https://github.com/whipper-team/whipper/blob/develop/README.md#configuration-file-documentation
track_template = album/%%A/%%y - %%d/%%t - %%n
disc_template  = album/%%A/%%y - %%d/%%A - %%d

[drive:TSSTcorp%3ACDDVDW%20SE-208DB%20%3ATS01]
vendor = TSSTcorp
model = CDDVDW SE-208DB
release = TS01
defeats_cache = True
read_offset = 6
