#!/bin/sh
set -e
DOTFILES="$HOME/.dotfiles"

_vim() {
  echo "Create temp and swap folder for vim"
  VIM_DIRS="vim vim/backup vim/swap vim/bundle"
  for vim_dir in $VIM_DIRS
  do
    mkdir -p "$DOTFILES/$vim_dir"
  done
  echo "Checking if Vundle exists"
  if [ ! -e vim/bundle/Vundle.vim ]
  then
    git clone git@github.com:gmarik/Vundle.vim.git vim/bundle/Vundle.vim
  fi
  echo "Installing Plugings with Vundle"
  vim +PluginInstall +qall
}

_symlinks() {
  echo "Making symlinks"
  symlinks="git/gitignore vim/vimrc \
    vim misc/latexmkrc zsh/zshrc zsh/zshenv zsh/zprofile"
  for s in $symlinks
  do
    file=$DOTFILES/$s
    target=$HOME/.$(basename "$s")
    echo "Linking $file -> $target"
    ln -sFf "$file" "$target" &
  done
  wait
  # XXX Fix symbolic link weirdness
  rm "$DOTFILES/vim/vim"
}

_chsh() {
  echo "Checking default shell"
  ZSH_PATH=$(which zsh)
  if [ "$SHELL" != "$ZSH_PATH" ]
  then
    echo "Set $ZSH_PATH as default shell"
    sudo chsh -s "$ZSH_PATH"
  fi
  echo "Done"
}

_git() {
  git config --global push.default simple
  git config --global commit.template "$DOTFILES/gitmessage"
  git config --global core.editor /usr/bin/vim
  git submodule init
  git submodule update
  git config --global core.excludesfile "$HOME/.gitignore"
  git submodule sync
  git submodule update --init
}

_chsh
_symlinks
_git
_vim
wait
