#!/bin/sh
set -e
DOTFILES="$HOME/.dotfiles"

_nvim() {
  nvim +PlugInstall +qall
}

_symlinks() {
  echo "Making symlinks"
  symlinks="misc/latexmkrc zsh/zshrc zsh/zshenv zsh/zprofile neovim/nvim neovim/nvimrc"
  for s in $symlinks
  do
    file=$DOTFILES/$s
    target=$HOME/.$(basename "$s")
    echo "Linking $file -> $target"
    ln -sFf "$file" "$target" &
  done
}

_chsh() {
  echo "Checking default shell"
  ZSH_PATH=$(which zsh)
  if [ "$SHELL" != "$ZSH_PATH" ]
  then
    echo "Set $ZSH_PATH as default shell"
    sudo chsh -s "$ZSH_PATH"
  fi
  echo "Done"
}

_git() {
  git config --global push.default simple
  git config --global commit.template "$DOTFILES/gitmessage"
  git config --global core.editor /usr/bin/vim
  git submodule init
  git submodule update
  git config --global core.excludesfile "$DOTFILES/.gitignore"
  git submodule sync
  git submodule update --init
}

_chsh
_symlinks
_git
_vim
_nvim
wait
