# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  # TODO
  # boot.initrd.luks.devices.sda2_crypt.device = "/dev/disk/by-uuid/c1403170-3734-41d4-b68f-889cb7829b8f";
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/mapper/${config.networking.hostName}_vg-root";
      fsType = "ext4";
    };
  fileSystems."/nix" =
    {
      depends = [ "/" ];
      device = "/nix";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/C0D1-C397";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/mapper/${config.networking.hostName}_vg-home";
      fsType = "ext4";
    };


  swapDevices =
    [{ device = "/dev/mapper/${config.networking.hostName}_vg-swap"; }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
