" Vim-Plug
  call plug#begin('~/.nvim/plugged')
    " File handling
    Plug 'kien/ctrlp.vim'

    " Syntax plugings
    Plug 'dag/vim-fish'
    Plug 'wting/rust.vim'
    Plug 'elixir-lang/vim-elixir'
    Plug 'hylang/vim-hy'

    " Syntax checking
    Plug 'scrooloose/syntastic'

    " Color scheme
    Plug 'altercation/vim-colors-solarized'

    " Surround text objects
    Plug 'tpope/vim-surround'

    " Better text navigation
    Plug 'jeffkreeftmeijer/vim-numbertoggle'
  call plug#end()

" Keyboard shortcuts
  let mapleader = ','
  " Normal Mode
    " Netrw splits
    nnoremap <C-n> :vs.<CR>
    nnoremap <C-s> :sp.<CR>
    nnoremap <C-l> :e.<CR>
    " Smarter text navigation
    nnoremap j gj
    nnoremap k gk
    " Pinky pain
    nore ; :
    " Run default macro
    nnoremap <Space> @q
    " Reload vim config
    nnoremap <leader>rl :source $MYVIMRC<CR>
    " Disable highlighting
    nnoremap <leader><space> :noh<cr>
    nnoremap / /\v
  " Visual Mode
    vnoremap / /\v
  " Young Padawan Mode
  :inoremap jk <esc>
  inoremap <esc> <NOP>
  noremap <Up> <NOP>
  noremap <Down> <NOP>
  noremap <Left> <NOP>
  noremap <Right> <NOP>
  noremap h <NOP>
  noremap j <NOP>
  noremap k <NOP>
  noremap l <NOP>

" Netrw
  let g:netrw_altv=1
  let g:netrw_liststyle=3

" Syntastic
  let g:syntastic_html_checkers=[]
  let g:syntastic_python_checkers=['pyflakes']

" Show unprintable characters
  set list
  set listchars=tab:>.,trail:.,extends:#,nbsp:.

" Column length
  set colorcolumn=80
  set tw=80

" Show commands while they're being typed
  set showcmd

" Line numbers
  set nu

" Folds
  set foldmethod=indent
  set foldlevelstart=2
  set foldminlines=2

" Use system clipboard
  set clipboard=unnamed

" Undo Levels
  set history=1000
  set undolevels=1000

" Indentation
  " When on, a <Tab> in front of a line inserts blanks according to
  " 'shiftwidth'.
  set smarttab
  " Copy indent from current line when starting a new line
  set autoindent
  " Do smart autoindenting when starting a new line.
  set smartindent
  " In Insert mode: Use the appropriate number of spaces to insert a <Tab>
  set expandtab
  " Number of spaces that a <Tab> in the file counts for.
  set tabstop=2
  " Returns the effective value of 'shiftwidth'. This is the
  " 'shiftwidth' value unless it is zero, in which case it is the
  " 'tabstop' value.
  set shiftwidth=0

" Matching
  set ignorecase
  set smartcase
  set gdefault
  set incsearch
  set showmatch
  set hlsearch

" Color Stuff
  set background=light
  colorscheme solarized
  let g:solarized_termcolors=256
  hi Normal ctermbg=none


" Customize Backup Dir location
  set backupdir=~/.nvim/backup/
  set directory=~/.nvim/swap/
